// Auth action types
export const AUTH_START = 'AUTH_START';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_ADMIN_LOGIN_SUCCESS = 'AUTH_ADMIN_LOGIN_SUCCESS';
export const AUTH_ADMIN_VERIFY_SUCCESS = 'AUTH_ADMIN_VERIFY_SUCCESS';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_HASH = 'SET_HASH';


// Content
export const CONTENT_START = 'CONTENT_START';
export const CONTENT_SUCCESS = 'CONTENT_SUCCESS';
export const CONTENT_FAIL = 'CONTENT_FAIL';



// Backend
export const ADMINS_RESET = 'ADMINS_RESET';
export const ADMINS_START = 'ADMINS_START';
export const ADMINS_SUCCESS = 'ADMINS_SUCCESS';
export const ADMINS_FAIL = 'ADMINS_FAIL';

export const CMS_RESET = 'CMS_RESET';
export const CMS_START = 'CMS_START';
export const CMS_SUCCESS = 'CMS_SUCCESS';
export const CMS_FAIL = 'CMS_FAIL';

export const DASHBOARD_RESET = 'DASHBOARD_RESET';
export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL';

export const FEATURES_RESET = 'FEATURES_RESET';
export const FEATURES_START = 'FEATURES_START';
export const FEATURES_SUCCESS = 'FEATURES_SUCCESS';
export const FEATURES_FAIL = 'FEATURES_FAIL';

export const ISSUES_RESET = 'ISSUES_RESET';
export const ISSUES_START = 'ISSUES_START';
export const ISSUES_SUCCESS = 'ISSUES_SUCCESS';
export const ISSUES_FAIL = 'ISSUES_FAIL';

export const LANGUAGES_RESET = 'LANGUAGES_RESET';
export const LANGUAGES_START = 'LANGUAGES_START';
export const LANGUAGES_SUCCESS = 'LANGUAGES_SUCCESS';
export const LANGUAGES_FAIL = 'LANGUAGES_FAIL';

export const PLATFORMS_RESET = 'PLATFORMS_RESET';
export const PLATFORMS_START = 'PLATFORMS_START';
export const PLATFORMS_SUCCESS = 'PLATFORMS_SUCCESS';
export const PLATFORMS_FAIL = 'PLATFORMS_FAIL';

export const ROLES_RESET = 'ROLES_RESET';
export const ROLES_START = 'ROLES_START';
export const ROLES_SUCCESS = 'ROLES_SUCCESS';
export const ROLES_FAIL = 'ROLES_FAIL';

export const USERS_RESET = 'USERS_RESET';
export const USERS_START = 'USERS_START';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';